Feat/CU-86a2czpac: add check box component
Hvasquezdev/kanban-task pull request #10
Opened 2024-02-29 16:20 UTC by Niicklz

## Descripción:

Desarrollar un componente reutilizable BaseCheckbox en React que sirva como elemento base para checkboxes dentro de nuestra aplicación.

## Cambios Realizados:

- [x] Se agregó componente base Checkbox de acuerdo al figma
![image](https://github.com/Hvasquezdev/kanban-task/assets/77895883/0c4cf84f-2549-42fe-b8b1-243eb5602ab5)
![image](https://github.com/Hvasquezdev/kanban-task/assets/77895883/7effb7da-ca5a-4a15-8308-395d100ee6a3)
![image](https://github.com/Hvasquezdev/kanban-task/assets/77895883/431a0d36-231f-4494-9e2d-cc5fc2f9de1d)

- [x] Se agregó prueba en el `app.tsx`
![image](https://github.com/Hvasquezdev/kanban-task/assets/77895883/cc25b68a-b705-4114-ae80-b025f5004748)

2024-02-29 17:14 UTC, angeleraser requested changes

2024-02-29 17:14 UTC, angeleraser commented on src/components/BaseCheckbox/BaseCheckbox.tsx
> +  onChange?: React.ChangeEventHandler<HTMLInputElement> | undefined;
Mejorar la interfaz del a propiead onChange.
```suggestion
  onChange?(value: boolean): void;
```

2024-02-29 18:57 UTC, angeleraser requested changes

2024-02-29 18:57 UTC, angeleraser commented on src/components/BaseCheckbox/BaseCheckbox.tsx
> +        id="checkbox"
Incluir propiedad `id` en las propiedades del componente y pasarla al **htmlFor** del label y **id** del input.

Al tener el **id** seteado de esta manera hace que colisionen los checkbox cuando 2 o mas componentes estan presentes en una misma vista, debido a que tienen el mismo id.

2024-02-29 19:14 UTC, angeleraser requested changes

2024-02-29 19:14 UTC, angeleraser commented on src/components/BaseCheckbox/BaseCheckbox.tsx
> +    'base-checkbox--fullWidth': fullWidth
Seguir la nomemclatura de `kebab-case` para las clases
```suggestion
    'base-checkbox--full-width': fullWidth
```

Recuerda actualizar en el archivo css tambien.

2024-03-01 00:30 UTC, angeleraser approved these changes
Aprobado

2024-03-01 01:12 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.tsx
> +      <input
El checkbox en su estado `checked` y `no-checked` debe contar con el mismo estilo que el figma

Asi se deberia ver cuando no esta `checked`, notese la diferencia en los bordes principalmente:
<img width="449" alt="Screenshot 2024-02-29 at 10 10 13 PM" src="https://github.com/Hvasquezdev/kanban-task/assets/35814981/bbac3525-b48d-43e9-959c-5d6db06514f3">

Asi se deberia ver cuanto esta `checked`, diferencia en los bordes, color y la flechita:
<img width="397" alt="Screenshot 2024-02-29 at 10 10 07 PM" src="https://github.com/Hvasquezdev/kanban-task/assets/35814981/48a1f34b-0a58-4b69-9550-9341d40da892">

2024-03-01 01:12 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +  width: 20px;
El alto y ancho del input debe ser `16px` segun indica el figma

2024-03-01 18:30 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +.base-checkbox::before {
Maneja los estilos desde el `before` o `after` no desde ambos, y cuando este checked simplemente cambias su color de border - fondo e imagen

2024-03-01 18:30 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +  border-radius: 4px;
El `border-radius` que se indica en figma son `2px`.

<img width="1230" alt="Screenshot 2024-03-01 at 3 23 41 PM" src="https://github.com/Hvasquezdev/kanban-task/assets/35814981/d6771a8e-0a0d-42a3-a012-cdf7f4e639b3">

2024-03-01 18:30 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +.base-checkbox::before {
Si no esta `checked` el cuadrado debe tener un background blanco segun lo especificado en figma

2024-03-01 18:30 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +  content: url('data:image/svg+xml,<svg width="10" height="8" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.27588 3.06593L4.03234 5.82239L9.03234 0.822388" stroke="whi
aqui lo correcto seria usar como imagen **solo** la flechita y el color de fondo lo controlas con el `background-image`, esto ayuda poder customizar el color de fondo en un futuro ya sea por dark-mode o si se agregan mas variantes de colores.

Inspeccionando el elemento en figma puedes copiar el svg de la flecha.
<img width="950" alt="Screenshot 2024-03-01 at 3 25 26 PM" src="https://github.com/Hvasquezdev/kanban-task/assets/35814981/8ba596d2-8257-4749-b33e-04928c78797f">

2024-03-01 20:17 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +  border-radius: 4px;
el `border-radius` debe ser 2px segun se indica en figma

2024-03-01 20:17 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +  padding: 10px;
El padding debe ser `12px` segun figma

2024-03-01 20:17 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +  text-transform: capitalize;
esto no debe ser capitalizado y el font-size debe ser `12px` segun figma

2024-03-01 21:35 UTC, angeleraser requested changes

2024-03-01 21:35 UTC, angeleraser commented on src/components/BaseCheckbox/BaseCheckbox.css
> +  border-radius: 2px;
El border-radius del checkbox deberia ser 4px segun el figma.

![image](https://github.com/Hvasquezdev/kanban-task/assets/59294770/64030e1d-2d27-4249-8538-f61bff68c92f)

2024-03-01 21:35 UTC, Hvasquezdev commented on src/components/BaseCheckbox/BaseCheckbox.css
> +  border-radius: 2px;
el `border-radius` de `2px` es solo para el cuadrito del checkbox, este debe llevar `4px`, no hay que perder de vista el figma, siempre verificar que los cambios que se hagan esten acordes

2024-03-01 22:11 UTC, angeleraser approved these changes
Aprobado

2024-03-01 22:33 UTC, Hvasquezdev approved these changes

2024-03-02 15:44 UTC, merged