CU-86a2edx4n - feat: add base modal component
Hvasquezdev/kanban-task pull request #15
Opened 2024-03-06 18:49 UTC by Niicklz

## Descripción:

Desarrollar un componente reutilizable BaseModal en React que sirva como elemento base para los modales dentro de nuestra aplicación.

## Cambios Realizados:

- [x] Se agregó componente base modal, con sus respectivas propiedades definidas en el figma
![image](https://github.com/Hvasquezdev/kanban-task/assets/77895883/79656349-bd32-406e-a245-e2877eed2f9f)

- [x] Se agregó una prueba en el `app.tsx` para ver su funcionamiento

2024-03-06 18:49 UTC, Hvasquezdev commented
Task linked: [CU-86a2edx4n Crear componente BaseModal](https://app.clickup.com/t/86a2edx4n)

2024-03-06 20:37 UTC, angeleraser commented on src/App.tsx
No permitir que cuando el modal este abierto haya scroll en la vista.
![image](https://github.com/Hvasquezdev/kanban-task/assets/59294770/492a0f4f-a9dc-479b-8fcc-98ea33279122)

2024-03-06 20:38 UTC, angeleraser commented on src/components/BaseModal/BaseModal.tsx
> +          if (e.key === 'Enter') onClose?.(!isClosed);
Cambiar la tecla a la Escape. 
```suggestion
          if (e.key === 'Enter') onClose?.(!isClosed);
```

2024-03-06 20:39 UTC, angeleraser commented on src/components/BaseModal/BaseModal.css
> +.base-modal-container__modal__header {
Esta estilo se puede unir con el de abajo para hacer esta regla.
```suggestion
.base-modal-container__modal__header, .base-modal-container__modal__content {
```

2024-03-06 20:44 UTC, angeleraser commented on src/components/BaseModal/BaseModal.tsx
> +  isClosed?: boolean;
De acuerdo al uso que se le da al estado: 
` const [isClosed, setIsClosed] = useState(false);`
```
    <BaseModal isClosed={isClosed} renderHeader={() => <h1>Header Testing</h1>} onClose={setIsClosed}>
        <p>Modal Content</p>
      </BaseModal>
```

Tendria mas sentido que el nombre de la propiedad sea open o isOpen, dado que comienza en `false` lo que indica que no esta `open`
```suggestion
  isOpen?: boolean;
```

2024-03-06 20:44 UTC, angeleraser commented on src/components/BaseModal/BaseModal.tsx
> +    'base-modal-container--open': isClosed,
Por que se esta manejando el estado de apertura con dos clases CSS?

Seria mas optimo que solo sea una,

2024-03-06 20:45 UTC, angeleraser commented on src/components/BaseModal/BaseModal.tsx
> +    <div className={`base-modal-container ${computedClassNames} ${className}`}>
Si el modal esta cerrado es decir, si `isOpen` es igual a `false` seria ideal que el modal no se renderizara en el DOM
```suggestion
    { isOpen ? <div className={`base-modal-container ${computedClassNames} ${className}`}> : null }
```

2024-03-06 21:00 UTC, angeleraser requested changes

2024-03-06 21:00 UTC, angeleraser commented on src/components/BaseModal/BaseModal.tsx
> +      <div className="base-modal-container__modal">
Usar el componente `BaseCard`

2024-03-06 23:37 UTC, angeleraser requested changes

2024-03-06 23:37 UTC, angeleraser commented on src/components/BaseModal/BaseModal.tsx
> +  }, [isOpen]);
Hacer un espacio entre lineas para mejorar legibilidad
```suggestion
  }, [isOpen]);
  
```

2024-03-06 23:37 UTC, angeleraser commented on src/components/BaseModal/BaseModal.tsx
> +    if (isOpen) {
Esto se puede realizar en una linea de codigo y evitamos el bloque if else
```suggestion
 document.body.style.overflow = isOpen ? 'hidden' ? 'auto'
```

2024-03-06 23:41 UTC, angeleraser requested changes

2024-03-06 23:41 UTC, angeleraser commented on src/components/BaseModal/BaseModal.tsx
> +  renderHeader?: () => React.ReactNode;
La propiedad renderHeader debe ser de tipo `React.ReactNode` no `() => React.ReactNode`.

Actualmente se utiliza asi:
```
<BaseModal isOpen={isOpen} renderHeader={() => <h1>Header Testing</h1>} onClose={setIsOpen}>
```
Y debe utilizarse de esta manera, pasandole el JSX, no una funcion que retorna JSX
```
<BaseModal isOpen={isOpen} renderHeader={<h1>Header Testing</h1>} onClose={setIsOpen}>
```

2024-03-06 23:49 UTC, angeleraser approved these changes
Aprobado

2024-03-07 23:08 UTC, Hvasquezdev commented on src/components/BaseModal/BaseModal.tsx
> +          {renderHeader && <div className="base-modal-container__modal__header">{renderHeader}</div>}
Las render props deben ser funciones, siguiendo las reglas del `Render Props pattern`, al ser funciones una de las ventajas que nos da es poder pasarle valores al componente o elemento que queramos renderizar, si bien este no es el caso donde queramos pasar valores hacia arriba, hay que cumplir con el patron y sus reglas.

[Render props](https://www.dhiwise.com/post/leveraging-react-render-props-for-flexible-component-composition#why-use-render-props-pattern-in-react-)

```suggestion
          {renderHeader && <div className="base-modal-container__modal__header">{renderHeader()}</div>}
```

En caso de querer que sea solo texto, sugiero cambiarle el nombre de la prop a otra que no inicie con `render`, por ejemplo `title` o algo por el estilo haciendo referencia al titulo que tendra el modal en su header

2024-03-07 23:08 UTC, Hvasquezdev commented on src/components/BaseModal/BaseModal.css
> +  z-index: 999 !important;
No usar `!important`, es una mala práctica.


![Panda rompiendo todo](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHA5cnYyMDE4Nm8ydHBzbHliM3ZubHN3bWhhZGFvOXp6bGkxOTBqYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/e24Q8FKE2mxRS/giphy.gif)

2024-03-09 00:35 UTC, Hvasquezdev approved these changes

2024-03-09 15:53 UTC, merged