Refactor/CU-86a2fck5a: add label to base select component
Hvasquezdev/kanban-task pull request #17
Opened 2024-03-08 21:10 UTC by Niicklz

## Descripción:

Se requiere agregar la propiedad label al componente BaseSelect para que permita mostrar ese valor en la interfaz de usuario.

## Cambios Realizados:

- [x] Se agrego el label al componente de acuerdo al figma
![image](https://github.com/Hvasquezdev/kanban-task/assets/77895883/dccb8312-a532-45bd-839c-aa6311df277d)

- [x] Se agrego la propiedad de ID, necesaria para su respectivo uso segun sea el caso

2024-03-08 21:10 UTC, Hvasquezdev commented
Task linked: [CU-86a2fck5a BaseSelect - Agregar label](https://app.clickup.com/t/86a2fck5a)

2024-03-08 21:57 UTC, angeleraser requested changes

2024-03-08 21:57 UTC, angeleraser commented on src/components/BaseSelect/BaseSelect.tsx
> +      {label && (
El label deberia ser un componente `BaseHeading`

2024-03-08 21:59 UTC, angeleraser requested changes

2024-03-08 21:59 UTC, angeleraser commented on src/App.tsx
Por que estan los cambios del `BaseModal`?

2024-03-09 15:56 UTC, angeleraser commented on src/components/BaseSelect/BaseSelect.tsx
> +      {label && (
Se debe estar pendiente cuando el componente BaseHeading permita cambiar el color de texto para integrarlo aqui.

2024-03-09 15:57 UTC, angeleraser approved these changes
Aprobado

2024-03-09 15:58 UTC, Hvasquezdev approved these changes

2024-03-09 16:01 UTC, merged