Feature/CU-86a2fh58h: add base layout
Hvasquezdev/kanban-task pull request #21
Opened 2024-03-13 00:01 UTC by Hvasquezdev

## Descripción:

Se requiere agregar el layout de la aplicacion el cual debe contener:

- Sidebar mobile y desktop
- Header mobile y desktop
- Menu (3 puntitos en el header)
- Contenedor principal donde se renderizara el contenido de la app
- Lista de boards en el sidebar

## Cambios Realizados:

- [x] Se creo un componente `BaseLayout` que se encargara de mostrar todo el contenido de la app como tambien de renderizar los componentes compartidos
- [ ] Se creo el componente `TheHeader` encargado de mostrar el header compartido de la app, como tambien de la funcionalidad de abrir y cerrar el sidebar menu
- [x] Se creo el componente `TheSidebar` encargado de mostrar el sidebar como tambien el menu flotante en la version mobile

## Checklist:

[Pasos a seguir para probar los cambios. (Eliminar)]

- [ ] Correr el servidor de desarrollo
- [ ] Comprobar que el diseno esta acorde al figma

## Notas Adicionales:

<img width="1440" alt="Screenshot 2024-03-12 at 8 56 44 PM" src="https://github.com/Hvasquezdev/kanban-task/assets/35814981/043f403e-d9de-4021-aa54-2d04020312bf">

<img width="467" alt="Screenshot 2024-03-12 at 8 56 53 PM" src="https://github.com/Hvasquezdev/kanban-task/assets/35814981/7d4fd217-d860-4e5a-98ef-045757596847">

2024-03-13 00:01 UTC, Hvasquezdev commented
Task linked: [CU-86a2fh58h Crear Layout de la aplicacion](https://app.clickup.com/t/86a2fh58h)

2024-03-13 01:04 UTC, angeleraser commented on src/components/BoardItem/index.ts
Falto hacer la importacion y exportacion del componente `BoardItem` aqui.

2024-03-13 01:06 UTC, angeleraser commented on src/components/Shared/TheHeader/TheHeader.tsx
> +    // eslint-disable-next-line
Esta regla que se esta evitando con el comentario pareceria necesaria desactivarla en general para todos, y asi nos evitamos usar el comentarion en el codigo.

Se sugiere desactivarla en el archivo `.eslintrc`.

2024-03-13 01:08 UTC, angeleraser commented on src/layouts/BaseLayout/BaseLayout.tsx
Que sucedio con este boton que muestra el sidebar cuando esta oculto en Desktop?
![image](https://github.com/Hvasquezdev/kanban-task/assets/59294770/b6ea3c35-678b-4c8c-9da6-b3301e7c09b0)

2024-03-13 01:09 UTC, angeleraser requested changes
Se requieren hacer correciones

2024-03-17 00:36 UTC, angeleraser approved these changes
Aprobado

2024-03-17 17:31 UTC, Niicklz approved these changes
Aprobao ingeniero

2024-03-17 22:52 UTC, merged