feat/CU-86a2ma91n: add board new column component
Hvasquezdev/kanban-task pull request #22
Opened 2024-03-14 17:12 UTC by Niicklz

## Descripción:

Componente para mostrar en la interfaz una columna vacia que al hacer click se debe abrir el modal para crear una columna en el board.

## Cambios Realizados:

- [x] Se agrego el componente BoardNewColumn
- [x] Se agrego prueba en el `app.tsx` 
![image](https://github.com/Hvasquezdev/kanban-task/assets/77895883/b594cdd9-f52e-471f-9cd2-8e3d53d180b2)

2024-03-14 17:12 UTC, Hvasquezdev commented
Task linked: [CU-86a2ma91n Crear componente BoardNewColumn](https://app.clickup.com/t/86a2ma91n)

2024-03-22 01:07 UTC, angeleraser commented on src/components/BoardNewColumn/BoardNewColumn.tsx
> +    <button className="new-column-btn" onClick={onClick}>
Es ideal usar el nombre del componente como nombre principal de la clase
```suggestion
    <button className="board-new-column" onClick={onClick}>
```

2024-03-22 01:14 UTC, angeleraser commented on src/components/BoardNewColumn/BoardNewColumn.css
> +  background-color: rgba(130, 143, 163, 0.2);
Si el color no esta en las variables css, lo ideal seria añadirlo como variable para que este disponible por si se necesita usar en otro lugar.

Sugiero crear una variable llamada:
--color-cloud-gray: #AFB6B9;

2024-03-22 01:15 UTC, angeleraser commented on src/components/BoardNewColumn/BoardNewColumn.css
> +.new-column-btn:hover {
Segun el figma, el efecto de hover seria poner el color de la fuente a `--color-main-purple`, se siguere remover el efecto de cambiar el fondo.

2024-03-22 01:17 UTC, anmdromeda commented on src/components/BoardNewColumn/BoardNewColumn.tsx
> +      + New Column
Cambiar este valor a un label opcional que se pueda pasar mediante props.
Tambien utilizar el componente `<BaseHeading size="xl">` para mostrar el texto del tamano correcto segun el figma.

2024-03-22 01:17 UTC, angeleraser requested changes
Se solicitan cambios.

2024-03-23 20:31 UTC, angeleraser approved these changes
Aprobado

2024-03-24 22:42 UTC, Hvasquezdev commented on src/components/BoardNewColumn/BoardNewColumn.tsx
> +      <BaseHeading variant="h6" size="xl" className="board-new-column__label">
Aca falta agregarle el `font-weight: bold` al texto

2024-03-24 22:42 UTC, Hvasquezdev commented on src/assets/css/colors.css
> +  --color-cloud-gray: #828fa333;
El color de fondo del boton es `#e9effa`

2024-03-24 22:42 UTC, Hvasquezdev commented on src/components/BoardNewColumn/BoardNewColumn.css
> +  color: var(--color-medium-grey);
El color no se esta aplicando al texto, sugiero agregarlo aumentando especificidad antes del hover para evitar pisarlo

```suggestion
.board-new-column.board-new-column__label {
  color: var(--color-medium-grey);
}
```

2024-03-24 23:56 UTC, Hvasquezdev approved these changes

2024-03-25 01:19 UTC, merged