Feat/CU-86a2cw9z9: add heading and texts components
Hvasquezdev/kanban-task pull request #7
Opened 2024-02-26 22:16 UTC by Niicklz

## Descripción:

Implementar un conjunto de componentes de tipografía en React utilizando TypeScript que sean fieles a la guía de estilos provista en Figma.

## Cambios Realizados:

- [x] Se agrego el componente BaseHeading

- [x] Se agrego el componente BaseText

- [x] Se agrego una exepcion al eslint para las props

- [x] Se agrego la fuente del proyecto al index.html

2024-02-26 22:16 UTC, Hvasquezdev commented
Task linked: [CU-86a2cw9z9 Agregar componentes de tipografia](https://app.clickup.com/t/86a2cw9z9)

2024-02-26 23:38 UTC, angeleraser commented on src/components/BaseHeading/BaseHeading.css
> +.heading {
Queda mas semantico e identificable utilizar para el nombre de las clases el prefijo o el mismo naming de los componentes.
`base-{component-name}`

2024-02-26 23:38 UTC, angeleraser commented on src/components/BaseHeading/BaseHeading.tsx
> +type BaseHeadingProps = {
Para las propiedades de los componentes es mejor utilizar `interface` debido a que al ser componentes base, es posible que se puedan tambien extender o usar como base para construir otros, por lo que semanticamente hablando, la forma que nos permite el `interface` con la palara `extends` para heredar de otra interfaz es mejor.

- `interface` para tipos complejos que ameriten estructura de datos como un objeto y sirva como base para otros.

- `type` para datos primitivos como un set finito de strings, booleano, composicion entre primitivos, payloads o un tipo de dato que no vaya a ser tratado desde el punto de vista de la POO, como el payload de un evento.

No hay mucha mas diferencia en como se usan, pero estaria bien unificarnos en este sentido.

@Hvasquezdev que opinas?

2024-02-26 23:38 UTC, angeleraser commented on src/components/BaseText/BaseText.css
> +.baseText {
Esta clase no se ajusta a la nomenclatura `kebab-case`.
`baseText` es `camelCase`.

2024-02-26 23:38 UTC, angeleraser commented on src/components/BaseText/BaseText.tsx
> +type BaseTextProps = {
Aqui aplicaria el mismo comentario sobre la definicion de las propiedades del componente hecho para el `BaseHeading`.

2024-02-26 23:38 UTC, angeleraser commented on src/components/BaseHeading/BaseHeading.css
> +}
Realizar un salto de linea entre las clases para mejorar legibilidad.

2024-02-27 01:34 UTC, angeleraser requested changes

2024-02-27 01:34 UTC, angeleraser commented on src/components/BaseText/BaseText.tsx
> +  return <p className={`base-text base-text--${size} base-text--${fontWeight} ${className}`}>{children}</p>;
Realizar formateo de componente para mejorar visualizacion, al igual que en el BaseHeading
```
<Tag>
  content
</Tag>
```

2024-02-27 18:46 UTC, Hvasquezdev commented on src/components/BaseText/BaseText.tsx
> +  size?: 'xl' | 'l' | 'm' | 's';
Actualizar los posibles valores por una version de 2 caracteres, y a su vez tambien realizar el cambio en el archivo css para que haga match con estos nuevos nombres

```suggestion
  size?: 'xl' | 'lg' | 'md' | 'sm';
```

2024-02-27 18:47 UTC, Hvasquezdev commented on src/components/BaseHeading/BaseHeading.tsx
> +  size?: 'xl' | 'l' | 'm' | 's';
Actualizar los posibles valores por una version de 2 caracteres, y a su vez tambien realizar el cambio en el archivo css para que haga match con estos nuevos nombres

```suggestion
  size?: 'xl' | 'lg' | 'md' | 'sm';
```

2024-02-27 19:15 UTC, Hvasquezdev commented on src/components/BaseHeading/BaseHeading.css
> +.base-heading--m {
Ajustar los `modifiers` de las clases acorde a los nuevos valores del `size`, ejemplo:

```suggestion
.base-heading--md {
```

2024-02-27 19:37 UTC, angeleraser approved these changes

2024-02-27 20:14 UTC, Hvasquezdev approved these changes

2024-02-27 22:39 UTC, merged